name: ecommerce_clothing
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  build_runner: ^2.10.4
  cupertino_icons: ^1.0.8
  flutter_gen_runner: ^5.12.0
  go_router: ^17.0.1
  get_it: ^9.2.0
  injectable: ^2.7.1+4
  injectable_generator: ^2.11.1
  bloc: ^9.2.0
  talker_bloc_logger: ^5.1.10
  animated_emoji: ^3.2.1
  flutter_screenutil: ^5.9.3
  dartz: ^0.10.1
  cached_network_image: ^3.4.1
  readmore: ^3.0.0
  my_flutter_toolkit:
    git:
      url: https://github.com/AmrSalahDev/MyFlutterToolKit.git
      ref: main
  lucide_icons_flutter: ^3.1.9
  flutter_staggered_grid_view: ^0.7.0
  animated_hint_textfield: ^1.1.1
  shimmer: ^3.0.0
  flutter_sticky_header: ^0.8.0
  rename: ^3.1.0
  change_app_package_name: ^1.5.0
  flutter_native_splash: ^2.4.7
  auto_size_text: ^3.0.0
  flutter_svg: ^2.2.3

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter


flutter_gen:
  output: lib/core/assets_gen

  integrations:
    image: true
    flutter_svg: true

  colors:
    inputs:
      - assets/color/colors.xml      

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/




  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
